@startuml
package dataAccessLayer{
package entities{
class HalfCabinet{
    -int kabin_no;
    -char kabinKisim;
    -Set<Location>locations();
}
HalfCabinet "1" *-- "15" Location:contains
class Location{
-id
-unit
-shelf
-Set<File>files();
}
class File{
-id
-String name
-int europaid
-String notes
-Set<Location>locations();
}
File "1..*"-"1..*" Location
(File,Location) .. File_Location
class File_Location{
-file_id
-location_id
}
}
class Baglanti{
public SessionFactory oturumÜreteci
    public Session oturum;
    public Transaction islem;
    public void ac(){
    public void kaydet(Object obj){
    public void guncelle(Object obj){
    public void kaydetVeyaGuncelle(Object obj){
}
}
package ana{
class ArsivMain{
    public static void main (String[] args) {
}
@enduml
